export default function Contact() {
  return (
    <>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
      <h1>Contact Page</h1>
    </>
  );
}
